.\" Man Page for ukui-greeter
.TH UKUI-GREETER 8 "March 05, 2018"
.SH "NAME"
ukui-greeter \- LightDM greeter for the UKUI desktop
.SH "SYNOPSIS"
.B ukui-greeter
.SH "DESCRIPTION"
.B UKUI Greeter
is a LightDM greeter for the UKUI desktop.
It is run by the LightDM daemon if configured in lightdm.conf.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
http://github.com/ukui/ukui-greeter/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
yanghao <yanghao@kylinos.cn> (2018)
.SH SEE ALSO
.B lightdm
